"""Tests for AES-256-GCM SecretBox + master-key resolution."""

from __future__ import annotations

import base64
import os
from pathlib import Path

import pytest

from app.core.secret_box import SecretBox, SecretBoxError


def test_round_trip_with_autogenerated_key(tmp_path: Path):
    key_file = tmp_path / "master.key"
    box = SecretBox(key_file=key_file, env={})

    blob = box.encrypt(b"sk-test-...")
    assert blob != b"sk-test-..."
    assert len(blob) >= 12 + 16
    assert box.decrypt(blob) == b"sk-test-..."

    # Master key file was created with the right size.
    assert key_file.exists()
    assert key_file.stat().st_size == 32


def test_master_key_file_reused_between_instances(tmp_path: Path):
    key_file = tmp_path / "master.key"
    a = SecretBox(key_file=key_file, env={})
    blob = a.encrypt(b"hello")

    b = SecretBox(key_file=key_file, env={})
    assert b.decrypt(blob) == b"hello"


def test_env_secret_key_overrides_file(tmp_path: Path):
    key_file = tmp_path / "master.key"
    # Pre-existing file with a different key — env should win.
    key_file.write_bytes(os.urandom(32))

    env_key_bytes = b"\x01" * 32
    env_key_hex = env_key_bytes.hex()
    box = SecretBox(key_file=key_file, env={"VIBE_SECRET_KEY": env_key_hex})

    blob = box.encrypt(b"secret payload")
    # Decrypting with a SecretBox that uses the file's key should fail.
    plain_box = SecretBox(key_file=key_file, env={})
    with pytest.raises(SecretBoxError):
        plain_box.decrypt(blob)


def test_env_secret_key_base64():
    env_key_bytes = b"\x02" * 32
    env_key_b64 = base64.b64encode(env_key_bytes).decode()
    assert len(env_key_b64) == 44
    box = SecretBox(key_file=None, env={"VIBE_SECRET_KEY": env_key_b64})
    blob = box.encrypt(b"x")
    assert box.decrypt(blob) == b"x"


def test_env_secret_key_invalid_format():
    with pytest.raises(SecretBoxError):
        SecretBox(key_file=None, env={"VIBE_SECRET_KEY": "too-short"})


def test_tampered_ciphertext_raises(tmp_path: Path):
    box = SecretBox(key_file=tmp_path / "master.key", env={})
    blob = bytearray(box.encrypt(b"hi"))
    blob[-1] ^= 0xFF  # flip a bit in the auth tag
    with pytest.raises(SecretBoxError):
        box.decrypt(bytes(blob))


def test_short_blob_raises(tmp_path: Path):
    box = SecretBox(key_file=tmp_path / "master.key", env={})
    with pytest.raises(SecretBoxError):
        box.decrypt(b"\x00" * 5)
